<?php
define('DB_ADRESS','127.0.0.1');
define('DB_USER','root');
define('DB_PASS','');
define('DB_NAME','mypath');
define('SITE_KEY','fpekd4R2+u/xTH-v2zpGLJN=gxBorft2awM%5jUTYQwvP');
define('NONCE_SALT','5Ci18;3kEy@Q61L7xTJz^3QBbhNhO0pB5LtaucyXdHL');
define('AUTH_SALT','u7aF27RWUjd\uNra8CR13b(kwleMdNw6PI&dfDf*jPBh');
?>